### ISSUE TITLE
StatefulSet restarter always restarts replica 0 immediately after initial rollout

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/commons-operator#111]
# Current behaviour

New restarter-enabled StatefulSet have their replica 0 restarted after the initial rollout is complete.

# Expected Behaviour

The initial rollout should be completed "normally" with no extra restarts.

# Why does this happen?

There is a race condition between Kubernetes' StatefulSet controller creating the first replica Pod and commons' StatefulSet restart controller adding the restart trigger labels. If the restarter loses the race then the first replica is created without the metadata, triggering a restart once it is added.

# What can we do about it?

Add a mutating webhook (see [the spike](https://github.com/stackabletech/commons-operator/tree/spike/sts-restarter-webhook)) that adds the relevant metadata. The webhook must not replace the existing controller, since webhook delivery is not reliable.

However, webhook delivery requires a bunch of extra infrastructure that we do not currently have, namely:

1. We must implement the K8s webhook HTTPS API (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/)
2. We must generate a TLS certificate and write that into the MWC

# Tasks

- [x] https://github.com/stackabletech/operator-rs/pull/1119
- [x] https://github.com/stackabletech/commons-operator/pull/387

# Definition of done

- [x] Webhook certificate is managed (provisioned and renewed) by the commons operator
- [x] The Webhook should apply the same `podTemplate` annotations as the controller currently does
  - [x] Initial STS rollout does not cause a restart (`STS.metadata.generation` should stay `1`)
- [x] Controller must still apply metadata if the webhook is disabled and/or fails (at the cost of still doing the extra restart in this case)
- [x] The webhook must fail open (`failurePolicy: Ignore`)
- [x] A Kuttl test should verify the above (maybe minus the `failurePolicy`)

<details>
<summary>Original ticket</summary>
The StatefulSet of a Superset cluster is immediately restarted after its creation. This should not be necessary and should be prevented.

```bash
$ kubectl describe statefulset simple-superset-node-default
...
Events:
  Type    Reason            Age                    From                    Message
  ----    ------            ----                   ----                    -------
  Normal  SuccessfulDelete  3m31s                  statefulset-controller  delete Pod simple-superset-node-default-0 in StatefulSet simple-superset-node-default successful
  Normal  SuccessfulCreate  2m59s (x2 over 3m31s)  statefulset-controller  create Pod simple-superset-node-default-0 in StatefulSet simple-superset-node-default successful
```

After the restart, the Superset pods are annotated as follows:

```yaml
annotations:
  configmap.restarter.stackable.tech/simple-superset-node-default: cf60300e-0c45-4ee2-b60c-de53b0084182/21998
  secret.restarter.stackable.tech/simple-superset-credentials: e0e4b781-46f9-44f4-80c8-a0876b91ed8b/16909
```

This could be an indication that the restart controller of the commons-operator is involved.

The commons-operator is busy while the StatefulSet is restarted:

```
2022-09-16T10:02:50.228971Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="pod.restarter.commons.stackable.tech" object=Pod.v1./simple-superset-node-default-0.default
2022-09-16T10:02:50.236144Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="pod.restarter.commons.stackable.tech" object=Pod.v1./simple-superset-node-default-0.default
2022-09-16T10:02:50.239371Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="statefulset.restarter.commons.stackable.tech" object=StatefulSet.v1.apps/simple-superset-node-default.default
2022-09-16T10:02:50.255219Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="statefulset.restarter.commons.stackable.tech" object=StatefulSet.v1.apps/simple-superset-node-default.default
2022-09-16T10:02:50.258511Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="pod.restarter.commons.stackable.tech" object=Pod.v1./simple-superset-node-default-0.default
2022-09-16T10:02:50.266146Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="pod.restarter.commons.stackable.tech" object=Pod.v1./simple-superset-node-default-0.default
2022-09-16T10:02:50.274647Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="statefulset.restarter.commons.stackable.tech" object=StatefulSet.v1.apps/simple-superset-node-default.default
2022-09-16T10:02:51.433621Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="pod.restarter.commons.stackable.tech" object=Pod.v1./simple-superset-node-default-0.default
2022-09-16T10:02:51.449009Z  INFO stackable_operator::logging::controller: Reconciled object controller.name="statefulset.restarter.commons.stackable.tech" object=StatefulSet.v1.apps/simple-superset-node-default.default
```
</details>

**Comment by fhennig** [comment]
So, is the mutating webhook that accepted solution to this problem? I see that this ticket is in refinement acceptance, I'd like to know the up- and downsides of this solution. Is there another way? how bad is:

> The downside is that doing a first webhook means doing a bunch of new scaffolding from scratch (certificates, kube API registration, etc)...

I personally wouldn't call this ticket refined, as I wouldn't know what to do. The ticket doesn't have tasks or even acceptance criteria.

**Comment by lfrancke** [comment]
I agree, this came up during the acceptance. So I'll move it back for now.

**Comment by lfrancke** [comment]
A few questions:
1. Do I understand it correctly that this will "only" fix the issue in most cases since delivery of webhooks is not reliable?
2. Do webhooks require any kind of extra privileges that we currently don't need?
3. Do webhooks work on OpenShift?
4. Does this need to be presented to the team again? I assume no because I believe this is the outcome of the last team session, right?

**Comment by teozkr** [comment]
> Do I understand it correctly that this will "only" fix the issue in most cases since delivery of webhooks is not reliable?

Yes, good old CAP strikes again. There's no way that we could possibly hook into an API in a way that is both:

1. Synchronous (happens before the write completes)
2. Exhaustive (never misses any events)
3. Reliable (doesn't bring down (parts of) the hooked API when it fails)

We could technically sacrifice any of these, but (to me) 2 and 3 are both far more vital than 1.

> Do webhooks require any kind of extra privileges that we currently don't need?

The operator and installer both need permission to work with `MutatingWebhookConfiguration` objects. Additionally, webhooks do introduce the risk of bugs and/or misconfiguration wreaking havoc on the larger system.

This design would allow users who are uncomfortable with running our webhook to simply not deploy the MWC, at the cost of still having to deal with this extra restart.

> Do webhooks work on OpenShift?

I haven't tested the spike against OS specifically, but Google seems to believe yes. I also remember noticing that certain parts of OS itself is implemented using webhooks.

> Does this need to be presented to the team again? I assume no because I believe this is the outcome of the last team session, right?

It might be worth bringing up at tomorrow's arch meeting. I'll add it to the list.

**Comment by lfrancke** [comment]
> Yes, good old CAP strikes again. There's no way that we could possibly hook into an API in a way that is both:

That's fine for me as the worst that can happen ist hat we get the extra restart, right?
Similar to the answer to question two.

Thank you. If the team is fine with this then I am as well.

**Comment by fhennig** [comment]
I think we didn't really discuss this broadly, I'll put it on the agenda for tomorrow, so we can have a brief look

**Comment by teozkr** [comment]
> That's fine for me as the worst that can happen ist hat we get the extra restart, right?

Yes.

**Comment by teozkr** [comment]
After some discussion with @sbernauer and @siegfriedweber we decided to push on with the webhook approach.

**Comment by lfrancke** [comment]
So this means refinement is done?

**Comment by sbernauer** [comment]
Teo did a handover with Siggi

**Comment by lfrancke** [comment]
This is an old ticket and while it is very well written and detailed I'd like to see a refinement/plan before we start implementing anything.

The plan should basically be a summary of past and current discussions and it should explain what we plan on doing now and how.

**Comment by sbernauer** [comment]
Meta: Add a mutating webhook that adds restarter annotations for ConfigMaps + Secret **instantly** before the first Pod is created. This way the first Pod doesn't need to be updated immediately after it's creation.
We already have a working spike by @nightkr 

Steps:

1. Extend stackable-webhook with supports for mutating webhooks (in addition to the current conversion webhooks)
2. Take @nightkr  spike branch and port it to the new stackable-webhook crate
  a. The whole TLS server, cert creation and rotation is already solved by stackable-webhook, so we don't need to think about that
  b. Things in kube-rs has changed since, needs some adopting
  c. Use the types from https://docs.rs/kube/latest/kube/core/admission/index.html, so we have better typing and ergonomics in Rust code -> Basically the same as we have for CRD versioning with https://docs.rs/kube/latest/kube/core/conversion/index.html.

Small side note: Technically this only works in case the StatefulSet is created after the mounted Secrets and ConfigMaps, but after quickly checking trino-operator I think in practice this shouldn't be a problem.

I now deeply understand all parts and already have a working prototype for all of this. Happy to answer detail questions :)
